import test from 'node:test';import assert from 'node:assert/strict';
import fixture from './fixtures/off-product.json' with {type:'json'};
import {mapOffFood,barcodeGET,normalizeBarcode,type BarcodeDependencies} from '../lib/open-food-facts.ts';
import {normalizedFoodQuery} from '../lib/food-cache.ts';
import {allowed,seed,apply} from '../lib/domain.ts';
const code=fixture.code;
function setup(overrides:Partial<BarcodeDependencies>={}){const calls:string[]=[];const d:BarcodeDependencies={owner:async()=> 'user',limit:async(u)=>{calls.push(u);},read:async()=>null,write:async()=>{calls.push('write');},fetch:async(input,init)=>{calls.push(String(input));assert.match(String(new Headers(init?.headers).get('User-Agent')),/^FitLive\//);assert.ok(init?.signal);return Response.json(fixture);},...overrides};return {d,calls};}
const request=()=>new Request(`https://fitlive.test/api/foods/barcode?code=${code}`);
test('OFF fixture maps into the shared candidate shape with attribution and serving',()=>{const f=mapOffFood(fixture.product,code);assert.equal(f.kcal,588);assert.equal(f.protein,25);assert.equal(f.servingGrams,32);assert.equal(f.brand,'Test brand');assert.equal(f.source,`Open Food Facts · ${code}`);assert.deepEqual(f.allergens,['peanut','milk']);});
test('missing, negative, blank and invalid nutrients remain null, recorded zero survives',()=>{const f=mapOffFood({nutriments:{proteins_100g:0,fat_100g:-1,fiber_100g:'',carbohydrates_100g:'NaN'}},code);assert.equal(f.protein,0);for(const key of ['kcal','fat','fiber','carbs'] as const)assert.equal(f[key],null);});
test('energy converts kJ without inventing grams for a liquid serving',()=>{assert.ok(Math.abs(mapOffFood({nutriments:{energy_100g:418.4}},code).kcal!-100)<1e-9);const f=mapOffFood({...fixture.product,serving_size:'250 ml',serving_quantity_unit:'ml'},code);assert.equal(f.servingGrams,null);assert.equal(f.kcal,null);assert.ok(f.labelNote);});
test('OFF allergens enter existing dietary checks and confirmed saves preserve source',()=>{const s=seed();s.profile.diet='omnivore';s.profile.allergies=['peanuts'];const candidate=mapOffFood(fixture.product,code);const food={...candidate,kcal:candidate.kcal!,protein:candidate.protein!,carbs:candidate.carbs!,fat:candidate.fat!,fiber:candidate.fiber!};assert.equal(allowed(food,s.profile),false);assert.throws(()=>apply(s,{type:'meal',food,grams:32},'off-test',1));s.profile.allergies=[];assert.equal(apply(s,{type:'meal',food,grams:32},'off-test',1).meals.at(-1)?.food.source,food.source);});
test('route requires auth before rate limit/cache/provider',async()=>{const {d,calls}=setup({owner:async()=>null});assert.equal((await barcodeGET(request(),d)).status,401);assert.equal(calls.length,0);});
test('per-user limit returns 429 without reaching cache or provider',async()=>{const {d,calls}=setup({limit:async()=>{throw new Error();}});assert.equal((await barcodeGET(request(),d)).status,429);assert.equal(calls.length,0);});
test('invalid barcode returns 400; leading zeros are preserved',async()=>{assert.equal(normalizeBarcode(' 0051 5002 55002 '),code);const {d}=setup();assert.equal((await barcodeGET(new Request('https://fitlive.test?code=abc'),d)).status,400);});
test('found product is cached, cache hits still require user rate limit',async()=>{const {d,calls}=setup();assert.equal((await barcodeGET(request(),d)).status,200);assert.ok(calls.includes('provider:open-food-facts'));assert.ok(calls.includes('write'));const cached=setup({read:async()=>mapOffFood(fixture.product,code)});assert.equal((await barcodeGET(request(),cached.d)).status,200);assert.deepEqual(cached.calls,['user']);});
test('not found is 404, provider errors, timeout and global budget exhaustion are honest 503s',async()=>{for(const status of [429,500,503]){const {d}=setup({fetch:async()=>new Response('',{status})});assert.equal((await barcodeGET(request(),d)).status,503);}const missing=setup({fetch:async()=>Response.json({status:0})});assert.equal((await barcodeGET(request(),missing.d)).status,404);const timed=setup({fetch:async()=>{throw new Error('timeout');}});assert.equal((await barcodeGET(request(),timed.d)).status,503);const global=setup({limit:async(user)=>{if(user.startsWith('provider:'))throw new Error();}});assert.equal((await barcodeGET(request(),global.d)).status,503);});
test('USDA query normalization shares case and whitespace equivalents',()=>{assert.equal(normalizedFoodQuery('  Greek   YOGURT '),normalizedFoodQuery('greek yogurt'));});
test('shared cache reuses normalized queries and keeps providers separate',async()=>{const {readFoodCache,writeFoodCache}=await import('../lib/food-cache.ts');const entries=new Map<string,Response>();const original=Object.getOwnPropertyDescriptor(globalThis,'caches');Object.defineProperty(globalThis,'caches',{configurable:true,value:{default:{put:async(req:Request,res:Response)=>{entries.set(req.url,res.clone());},match:async(req:Request)=>entries.get(req.url)?.clone()}}});try{await writeFoodCache('usda-v1',normalizedFoodQuery(' OATS '),[fixture],3600);assert.deepEqual(await readFoodCache('usda-v1',normalizedFoodQuery('oats')),[fixture]);assert.equal(await readFoodCache('off-v1','oats'),null);}finally{if(original)Object.defineProperty(globalThis,'caches',original);else Reflect.deleteProperty(globalThis,'caches');}});
