import test from "node:test";import assert from "node:assert/strict";
import {catalogue,exerciseMatches,exerciseIdentity} from "../lib/exercises/catalogue.ts";
import {migrateExercises,confirmExerciseMatch} from "../lib/exercises/migration.ts";
import {seed,apply,validateSnapshot} from "../lib/domain.ts";
const now=new Date("2026-09-09T15:00:00Z");
test("catalogue IDs are unique and common spelling variants resolve consistently",()=>{assert.equal(new Set(catalogue.map(e=>e.id)).size,catalogue.length);assert.equal(exerciseIdentity("Inclined dumble press"),exerciseIdentity("Incline dumbbell press"));assert.ok(exerciseMatches("Dumbbell Bench Press")[0].score===1);});
test("migration preserves every recorded field, is repeatable and survives snapshot validation",()=>{const s=seed(now);const migrated=migrateExercises(s);assert.deepEqual(migrated.workouts.map(w=>({...w,sets:w.sets.map(set=>{const original={...set};delete original.exerciseId;return original;})})),s.workouts);assert.ok(migrated.workouts.every(w=>w.sets.every(x=>!!x.exerciseId)));assert.deepEqual(migrateExercises(migrated),migrated);const validated=validateSnapshot(migrated);assert.equal(validated.workouts[0].sets[0].exerciseId,migrated.workouts[0].sets[0].exerciseId);});
test("ambiguous identities remain separate until confirmed and no sets are discarded",()=>{const s=seed(now);s.workouts[0].sets[0].exercise="Dumbbell Pres";const m=migrateExercises(s);const match=m.exerciseMatches?.find(x=>x.name==="Dumbbell Pres");assert.ok(match);const count=m.workouts.reduce((n,w)=>n+w.sets.length,0);confirmExerciseMatch(m,match.legacyId,match.candidateId);assert.equal(m.workouts.reduce((n,w)=>n+w.sets.length,0),count);assert.equal(m.workouts[0].sets[0].exerciseId,match.candidateId);});
test("custom creation cannot fork an existing exercise identity",()=>{const e=catalogue.find(e=>e.modality==="strength"&&e.name==="Dumbbell Bench Press")!;assert.throws(()=>apply(seed(now),{type:"exercise-create",exercise:{...e,id:"custom:fixture"}},"fixture",1,now),/existing exercise/);});
