CREATE TABLE accounts (
 owner_id VARCHAR(255) PRIMARY KEY,
 version BIGINT NOT NULL DEFAULT 0,
 data TEXT NOT NULL,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE operations (
 owner_id VARCHAR(255) NOT NULL REFERENCES accounts(owner_id) ON DELETE CASCADE,
 operation_id VARCHAR(160) NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(owner_id,operation_id)
);
CREATE TABLE device_tokens (
 token_hash VARCHAR(64) PRIMARY KEY,
 owner_id VARCHAR(255) NOT NULL REFERENCES accounts(owner_id) ON DELETE CASCADE,
 expires_at TIMESTAMPTZ NOT NULL
);
