"use client";
import {useEffect,useRef,useState} from 'react';
import {Camera,ScanLine} from 'lucide-react';
import type {FoodCandidate} from '@/lib/food-data';
type Detector={detect:(source:HTMLVideoElement)=>Promise<{rawValue:string}[]>};
type DetectorConstructor={new(options:{formats:string[]}):Detector;getSupportedFormats:()=>Promise<string[]>};
export function BarcodeFood({onFound,onManual}:{onFound:(food:FoodCandidate)=>void;onManual:()=>void}){
 const [code,setCode]=useState(''),[busy,setBusy]=useState(false),[camera,setCamera]=useState(false),[message,setMessage]=useState('');
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),generation=useRef(0),request=useRef<AbortController|null>(null);
 const stop=()=>{generation.current++;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(timer.current)clearTimeout(timer.current);};
 useEffect(()=>{const lifetime=generation;return()=>{lifetime.current++;stream.current?.getTracks().forEach(t=>t.stop());if(timer.current)clearTimeout(timer.current);request.current?.abort();};},[]);
 async function lookup(value:string){stop();setCamera(false);setCode(value);setBusy(true);setMessage('Looking up the package…');request.current?.abort();const controller=new AbortController();request.current=controller;
  try{const response=await fetch(`/api/foods/barcode?code=${encodeURIComponent(value)}`,{signal:controller.signal});const result=await response.json() as {food?:FoodCandidate;error?:string};if(!response.ok||!result.food)throw new Error(result.error??'Lookup unavailable. Enter the package label instead.');if(!controller.signal.aborted)onFound(result.food);}catch(e){if(!controller.signal.aborted)setMessage(e instanceof Error?e.message:'Lookup unavailable. Try manual entry.');}finally{if(!controller.signal.aborted)setBusy(false);}
 }
 async function start(){stop();const token=generation.current;const Constructor=(window as unknown as {BarcodeDetector?:DetectorConstructor}).BarcodeDetector;
  if(!Constructor||!navigator.mediaDevices?.getUserMedia){setMessage('Camera scanning is not supported in this browser. Enter the barcode number below.');return;}
  try{const formats=(await Constructor.getSupportedFormats()).filter(x=>['ean_13','ean_8','upc_a','upc_e','itf'].includes(x));if(token!==generation.current)return;if(!formats.length)throw new Error();setCamera(true);setMessage('Point at the package barcode. No photo is uploaded.');const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});if(token!==generation.current){media.getTracks().forEach(t=>t.stop());return;}stream.current=media;if(!video.current)throw new Error();video.current.srcObject=media;await video.current.play();if(token!==generation.current)return;const detector=new Constructor({formats});
   const scan=async()=>{if(token!==generation.current||!video.current)return;try{const results=await detector.detect(video.current);if(token!==generation.current)return;const found=results.find(x=>/^(?:\d{8}|\d{12}|\d{13}|\d{14})$/.test(x.rawValue));if(found){await lookup(found.rawValue);return;}}catch{if(token!==generation.current)return;}timer.current=setTimeout(()=>void scan(),400);};void scan();
  }catch{if(token===generation.current){stop();setCamera(false);setMessage('Camera unavailable or permission denied. You can still enter the barcode number below.');}}
 }
 return <section className="barcode-food"><div className="row spread"><h3><ScanLine size={18}/> Packaged food</h3><button type="button" className="secondary" disabled={busy||camera} onClick={()=>void start()}><Camera size={16}/> Scan barcode</button></div><p className="muted">Scan or enter the number, then check the package label before logging.</p>{camera&&<div className="barcode-camera"><video ref={video} muted playsInline aria-label="Live package barcode camera"/><button type="button" className="secondary" onClick={()=>{stop();setCamera(false);setMessage('Camera stopped. Manual entry is available.');}}>Stop camera</button></div>}<div className="search-row"><input aria-label="Package barcode number" inputMode="numeric" autoComplete="off" maxLength={24} placeholder="Barcode number" value={code} onChange={e=>setCode(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!busy&&code.trim()){e.preventDefault();void lookup(code);}}}/><button type="button" className="secondary" disabled={busy||!code.trim()} onClick={()=>void lookup(code)}>{busy?'Looking up…':'Find package'}</button></div>{message&&<p role="status">{message}</p>}<button type="button" className="text-button" onClick={()=>{stop();request.current?.abort();onManual();}}>Enter label values myself</button></section>;
}
