"use client";
import {useEffect,useRef,useState} from 'react';
import {SetStepper} from './set-controls';
import {displayLoad,toKg,type LoadUnit} from '@/lib/load-units';
import type {SetLog} from '@/lib/domain';
export function EditableSet({set,unit,onChange,older=false,disabled=false,voice}:{set:SetLog;unit:LoadUnit;onChange:(next:SetLog|null)=>Promise<boolean>;older?:boolean;disabled?:boolean;voice?:{revision:number;patch:{load?:number;reps?:number}}}){
 const [editing,setEditing]=useState(false),[confirmed,setConfirmed]=useState(false),[pending,setPending]=useState<SetLog|null|undefined>(),[saving,setSaving]=useState(false);const timer=useRef<ReturnType<typeof setTimeout>|null>(null),point=useRef<{x:number;y:number}|null>(null);
 const cancel=()=>{if(timer.current)clearTimeout(timer.current);timer.current=null;};
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);
 const [seen,setSeen]=useState(voice?.revision);if(voice&&voice.revision!==seen){setSeen(voice.revision);setEditing(true);setPending({...set,...voice.patch});}
 async function commit(next:SetLog|null){if(disabled||saving)return;if(older&&!confirmed){setPending(next);return;}setSaving(true);try{if(await onChange(next))setPending(undefined);}finally{setSaving(false);}}
 const current=pending??set;
 return <div className="editable-set" tabIndex={0} aria-label={`${set.exercise}, ${set.reps} reps. Hold or swipe left to correct. Keyboard: Shift F10.`} onContextMenu={e=>{e.preventDefault();if(!disabled)setEditing(true);}} onKeyDown={e=>{if(e.key==='F10'&&e.shiftKey){e.preventDefault();setEditing(true);}if(e.key==='Escape'){setEditing(false);setPending(undefined);}}} onPointerDown={e=>{if(e.target!==e.currentTarget&&editing)return;point.current={x:e.clientX,y:e.clientY};cancel();timer.current=setTimeout(()=>{if(!disabled)setEditing(true);},600);}} onPointerMove={e=>{const p=point.current;if(p&&(Math.abs(e.clientX-p.x)>12||Math.abs(e.clientY-p.y)>12))cancel();}} onPointerUp={e=>{cancel();const p=point.current;if(p&&e.clientX-p.x< -55&&Math.abs(e.clientY-p.y)<35&&!disabled)setEditing(true);point.current=null;}} onPointerCancel={()=>{cancel();point.current=null;}}>
 <div className="row spread"><span>{set.exercise}{set.editedAt&&<small className="edited-tag">edited</small>}</span><span>{set.reps} × {set.load?`${displayLoad(set.load,unit)} ${unit}`:'bodyweight'} · RPE {set.rpe??'—'}</span></div>
 {editing&&<div className="inline-set-editor"><div className="quick-set-controls"><SetStepper label={`Load · ${unit}`} value={displayLoad(current.load,unit)} min={0} max={unit==='kg'?500:1100} step={unit==='kg'?2.5:5} onChange={n=>void commit({...current,load:toKg(n,unit)})}/><SetStepper label="Reps" value={current.reps} min={1} max={100} step={1} onChange={n=>void commit({...current,reps:Math.round(n)})}/></div><label className="field">Effort · optional<select disabled={saving||disabled} value={current.rpe??""} onChange={e=>void commit({...current,rpe:e.target.value?Number(e.target.value):undefined})}><option value="">Not recorded</option>{[1,2,3,4,5,6,7,8,9,10].map(n=><option key={n} value={n}>{n}</option>)}</select></label>{pending!==undefined&&<button type="button" className="primary" disabled={saving||disabled} onClick={async()=>{setSaving(true);try{if(await onChange(pending)){setConfirmed(true);setPending(undefined);}}finally{setSaving(false);}}}>{older&&!confirmed?'Confirm older session correction':'Apply voice correction'}</button>}<button type="button" className="text-button danger" disabled={saving||disabled} onClick={()=>void commit(null)}>Delete set</button><button type="button" className="text-button" onClick={()=>{setEditing(false);setPending(undefined);}}>Done</button></div>}
 </div>;
}
