"use client";
import {displayLoad} from "@/lib/load-units";
import {useId,useMemo,useState} from "react";
import {catalogue,exerciseMatches,normalizeExercise,similarity,type Exercise} from "@/lib/exercises/catalogue";
import type {State,Command} from "@/lib/domain";
export function ExercisePicker({state,value,onSelect,act}:{state:State;value:string;onSelect:(e:Exercise)=>void;act:(c:Command,close?:boolean)=>Promise<boolean>}){
 const id=useId(),[query,setQuery]=useState(""),[open,setOpen]=useState(false),[index,setIndex]=useState(0),[creating,setCreating]=useState(false),[error,setError]=useState("");
 const library=useMemo(()=>[...(state.customExercises??[]),...catalogue].filter(e=>e.modality==="strength"),[state.customExercises]);
 const results=useMemo(()=>{const q=normalizeExercise(query);const recent=[...state.workouts].sort((a,b)=>b.date.localeCompare(a.date)).flatMap(w=>w.sets);const program=state.program?.sessions.flatMap(s=>s.exercises)??[];
  return library.filter(e=>!q||normalizeExercise([e.name,...e.aliases,...e.primaryMuscles,...e.secondaryMuscles].join(" ")).includes(q)||similarity(query,e.name)>=.6).map(e=>{const at=recent.findIndex(s=>s.exerciseId===e.id);return {e,rank:at>=0?at:program.some(p=>p.exerciseId===e.id)?10000:20000,last:at>=0?recent[at]:null};}).sort((a,b)=>a.rank-b.rank||a.e.name.localeCompare(b.e.name)).slice(0,18);
 },[query,library,state.workouts,state.program]);
 function choose(e:Exercise){onSelect(e);setOpen(false);setQuery("");}
 return <div className="exercise-picker"><input role="combobox" aria-label="Find an exercise" aria-expanded={open} aria-controls={id} aria-autocomplete="list" aria-activedescendant={open&&results[index]?`${id}-${index}`:undefined} value={open?query:value} placeholder="Search exercises or muscles" onFocus={()=>{setOpen(true);setQuery("");setIndex(0);}} onChange={e=>{setQuery(e.target.value);setIndex(0);}} onKeyDown={e=>{if(e.key==="ArrowDown"){e.preventDefault();setOpen(true);setIndex(i=>Math.max(0,Math.min(i+1,results.length-1)));}if(e.key==="ArrowUp"){e.preventDefault();setIndex(i=>Math.max(0,i-1));}if(e.key==="Escape")setOpen(false);if(e.key==="Enter"&&open){e.preventDefault();if(results[index])choose(results[index].e);}}}/>
 {open&&<div className="exercise-results"><ul id={id} role="listbox" aria-label="Exercises">{results.length===0&&<li role="presentation">No matching exercises. Try another name or create your own.</li>}{results.map(({e,rank,last},i)=><li key={e.id} id={`${id}-${i}`} role="option" aria-selected={index===i} onMouseDown={event=>event.preventDefault()} onClick={()=>choose(e)}><strong>{e.name}</strong><small>{rank<10000?"You did this recently":rank<20000?"In your program":e.primaryMuscles.join(" · ")} · {e.equipment}{last?` · last ${displayLoad(last.load,state.preferences?.loadUnit??"kg")} ${state.preferences?.loadUnit??"kg"} × ${last.reps}`:""}</small></li>)}</ul><button type="button" className="text-button" onClick={()=>{setCreating(true);setError("");}}>+ Create {query.trim()?`“${query.trim()}”`:"a custom exercise"}</button><button type="button" className="text-button" onClick={()=>setOpen(false)}>Close search</button></div>}
 {creating&&<div className="custom-exercise"><h4>Create your exercise</h4><p>Choose its equipment and main muscle once. Similar exercises should use the existing entry.</p><label className="field">Name<input value={query} maxLength={100} onChange={e=>setQuery(e.target.value)}/></label>{exerciseMatches(query,state.customExercises).slice(0,3).map(({exercise})=><button type="button" className="secondary" key={exercise.id} onClick={()=>{choose(exercise);setCreating(false);}}>Use {exercise.name}</button>)}<label className="field">Equipment<select id={`${id}-equipment`} defaultValue="dumbbell">{["barbell","dumbbell","cable","machine","bodyweight","kettlebell","band"].map(x=><option key={x}>{x}</option>)}</select></label><label className="field">Main muscle<select id={`${id}-muscle`}>{["Quads","Hamstrings","Glutes","Back","Chest","Shoulders","Biceps","Triceps","Core","Calves"].map(x=><option key={x}>{x}</option>)}</select></label><button type="button" className="primary" onClick={async()=>{setError("");if(!query.trim()){setError("Enter a name.");return;}if((exerciseMatches(query,state.customExercises)[0]?.score??0)>=.9){setError("This closely matches an existing exercise. Select it above to keep your history together.");return;}const equipment=(document.getElementById(`${id}-equipment`) as unknown as HTMLSelectElement).value as Exercise["equipment"];const e:Exercise={id:"custom:"+crypto.randomUUID(),name:query.trim(),aliases:[],primaryMuscles:[(document.getElementById(`${id}-muscle`) as unknown as HTMLSelectElement).value],secondaryMuscles:[],equipment,minReps:8,maxReps:12,increment:equipment==="dumbbell"?2:2.5,modality:"strength"};if(await act({type:"exercise-create",exercise:e},false)){choose(e);setCreating(false);}}}>Create & use</button><button type="button" className="secondary" onClick={()=>setCreating(false)}>Cancel</button>{error&&<p role="alert">{error}</p>}</div>}
 </div>;
}
export function ExerciseMatchReview({state,act,busy}:{state:State;busy:boolean;act:(c:Command,close?:boolean)=>Promise<boolean>}){if(!state.exerciseMatches?.length)return null;return <section className="panel small-space"><h3>Keep your exercise history together</h3><p>These names may refer to catalogue exercises. Every original set stays intact; only confirmed identities merge.</p>{state.exerciseMatches.map(m=><div key={m.legacyId} className="history"><p>{m.name} → {catalogue.find(e=>e.id===m.candidateId)?.name}</p><button className="secondary" disabled={busy} onClick={()=>void act({type:"exercise-match",legacyId:m.legacyId,targetId:m.candidateId},false)}>Same exercise</button><button className="text-button" disabled={busy} onClick={()=>void act({type:"exercise-match",legacyId:m.legacyId,targetId:m.legacyId},false)}>Keep my custom exercise</button></div>)}</section>;}
