"use client";
import {useEffect,useRef,useState} from 'react';
import {dateKey,recovery,totals,type State} from '@/lib/domain';
import {weekDates} from '@/lib/chart-data';
export function ChangingNumber({value}:{value:number}){const [shown,setShown]=useState(value),previous=useRef(value);useEffect(()=>{const from=previous.current;previous.current=value;if(from===value)return;const motion=window.matchMedia('(prefers-reduced-motion: reduce)');let frame=0;const start=performance.now();function tick(now:number){const p=motion.matches?1:Math.min(1,(now-start)/350);setShown(Math.round(from+(value-from)*(1-Math.pow(1-p,3))));if(p<1)frame=requestAnimationFrame(tick);}frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[value]);return <><span aria-hidden="true">{shown}</span><span className="sr-only">{value}</span></>;}
export function Glance({state,onOpen}:{state:State;onOpen:(section:'recovery'|'food'|'training')=>void}){
 const day=dateKey(new Date(),state.profile.timezone),r=recovery(state),t=totals(state,day),logged=state.meals.some(m=>m.date===day);const days=weekDates(state);const completed=state.workouts.filter(w=>days.includes(w.date)&&w.status==='completed').length;
 const items=[{name:'Protein',value:logged?Math.round(t.protein):null,target:state.profile.protein,unit:'g',note:logged?`${Math.max(0,Math.round(state.profile.protein-t.protein))} g to your target`:'No meals recorded today',section:'food' as const},{name:'Energy',value:logged?Math.round(t.kcal):null,target:state.profile.calories,unit:'kcal',note:'Recorded meals only',section:'food' as const},{name:'Last 7 days',value:completed,target:state.profile.days,unit:'sessions',note:'Completed · weekly goal',section:'training' as const}];
 return <section className="glance-grid" aria-label="Today at a glance"><button className="glance-tile recovery-glance" onClick={()=>onOpen('recovery')}><span className="eyebrow">Recovery</span><strong>{!r.latest||r.stale?'Needs context':r.band}</strong><span className="recovery-sources">{r.latest&&!r.stale?'Current data':'Awaiting data'} · {r.days>=7?'Baseline ready':`${r.days}/7 baseline days`}</span><small>{r.confidence} confidence · {r.latest&&r.latest.sleep!==null&&!r.stale?`${Math.floor(r.latest.sleep/60)}h ${Math.round(r.latest.sleep%60)}m sleep`:'Add today’s check-in'}</small></button>{items.map(item=><button className="glance-tile" key={item.name} onClick={()=>onOpen(item.section)}><span className="eyebrow">{item.name}</span><strong>{item.value===null?'—':<ChangingNumber value={item.value}/>}<small> / {item.target} {item.unit}</small></strong><span className="glance-track" aria-hidden="true"><i style={{width:`${Math.min(100,(item.value??0)/item.target*100)}%`}}/></span><small>{item.note}</small></button>)}</section>;
}
