"use client";
import { useState } from "react";
import { type State, type Command, allowed } from "@/lib/domain";
import { foodLibrary } from "@/lib/planning";
import { checkCart, cartPolicy } from "@/lib/grocery";
export function GroceryReview({state:s,busy,act}:{state:State;busy:boolean;act:(command:Command,close?:boolean)=>Promise<boolean>}){
 const [items,setItems]=useState([{foodId:"",grams:500,estimateCents:0}]);const [error,setError]=useState("");
 const foods=foodLibrary(s).filter(f=>allowed(f,s.profile)&&(s.mode==="demo"||!f.source.startsWith("Demo")));
 const cart=s.cart,check=checkCart(s,cart?.items??items),stale=cart&&cart.policy!==cartPolicy(s);
 async function preview(){setError("");if(items.some(i=>!i.foodId)){setError("Choose a food for every row.");return;}await act({type:"cart-preview",items},false);}
 return <details className="panel small-space"><summary>Review a grocery plan · sandbox</summary><p>This sandbox uses your price estimates. Approval saves the plan only; it does not contact a retailer or place an order.</p>{items.map((item,i)=><div className="review-food-row" key={i}><label><span>Food record</span><select value={item.foodId} onChange={e=>setItems(items.map((v,j)=>j===i?{...v,foodId:e.target.value}:v))}><option value="">Choose food</option>{foods.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label><span>Quantity (g)</span><input type="number" min={1} max={100000} value={item.grams} onChange={e=>setItems(items.map((v,j)=>j===i?{...v,grams:Number(e.target.value)}:v))}/></label><label><span>Estimated cost for this quantity ($)</span><input type="number" min={0} max={10000} step="0.01" value={item.estimateCents/100} onChange={e=>setItems(items.map((v,j)=>j===i?{...v,estimateCents:Math.round(Number(e.target.value)*100)}:v))}/></label><button className="text-button" disabled={items.length===1} onClick={()=>setItems(items.filter((_,j)=>j!==i))}>Remove</button></div>)}<div className="row wrap"><button className="secondary" disabled={items.length>=40||busy} onClick={()=>setItems([...items,{foodId:"",grams:500,estimateCents:0}])}>Add food</button><button className="primary" disabled={busy||!foods.length} onClick={()=>void preview()}>Prepare review</button></div>{!foods.length&&<p>Add confirmed food records before preparing a cart.</p>}{error&&<p role="alert">{error}</p>}{cart&&<div className="small-space"><h4>{cart.status==="approved"?"Plan approved · no order placed":"Ready for your review"}</h4><ul>{cart.items.map(i=><li key={i.foodId}>{foods.find(f=>f.id===i.foodId)?.name??"Unavailable food"}: {i.grams} g · estimated ${(i.estimateCents/100).toFixed(2)}</li>)}</ul><p>Estimated total ${(check.total/100).toFixed(2)} · weekly budget ${(check.budget/100).toFixed(2)}</p>{check.issues.map(x=><p role="alert" key={x}>{x}</p>)}{stale&&<p role="alert">Preferences changed. Prepare a new review.</p>}<button className="primary" disabled={busy||!!stale||check.issues.length>0||cart.status==="approved"} onClick={()=>void act({type:"cart-approve",id:cart.id},false)}>Approve sandbox plan</button></div>}</details>;
}
